GET http://localhost:8080/
Accept: application/json
Authorization: Bearer xyz

###

GET http://localhost:8080/

###

POST http://localhost:8080/api/authenticate
Content-Type: application/json

{
  "username": "test",
  "password": "pass"
}

###

