-- MySQL Script generated by MySQL Workbench
-- Fri May  8 17:07:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`
(
    `id`           INT         NOT NULL AUTO_INCREMENT,
    `username`     VARCHAR(45) NOT NULL,
    `password`     CHAR(60)    NOT NULL,
    `display_name` VARCHAR(45) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe`
(
    `id`               INT           NOT NULL AUTO_INCREMENT,
    `name`             VARCHAR(45)   NOT NULL,
    `description`      VARCHAR(1000) NOT NULL,
    `created_at`       DATETIME      NOT NULL,
    `author_id`        INT           NOT NULL,
    `preparation_time` VARCHAR(45)   NOT NULL,
    `image_url` VARCHAR(255) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_recipe_user_idx` (`author_id` ASC),
    CONSTRAINT `fk_recipe_user`
        FOREIGN KEY (`author_id`)
            REFERENCES `user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingredient`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_ingredient`
(
    `recipe_id`     INT         NOT NULL,
    `ingredient_id` INT         NOT NULL,
    `amount`        VARCHAR(45) NOT NULL,
    INDEX `fk_recipe_ingredient_recipe1_idx` (`recipe_id` ASC),
    PRIMARY KEY (`recipe_id`, `ingredient_id`),
    INDEX `fk_recipe_ingredient_ingredient1_idx` (`ingredient_id` ASC),
    CONSTRAINT `fk_recipe_ingredient_recipe1`
        FOREIGN KEY (`recipe_id`)
            REFERENCES `recipe` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_recipe_ingredient_ingredient1`
        FOREIGN KEY (`ingredient_id`)
            REFERENCES `ingredient` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_category`
(
    `recipe_id`   INT NOT NULL,
    `category_id` INT NOT NULL,
    INDEX `fk_recipe_category_recipe1_idx` (`recipe_id` ASC),
    INDEX `fk_recipe_category_category1_idx` (`category_id` ASC),
    PRIMARY KEY (`recipe_id`, `category_id`),
    CONSTRAINT `fk_recipe_category_recipe1`
        FOREIGN KEY (`recipe_id`)
            REFERENCES `recipe` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_recipe_category_category1`
        FOREIGN KEY (`category_id`)
            REFERENCES `category` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipe_instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_instruction`
(
    `id`        INT           NOT NULL AUTO_INCREMENT,
    `text`      VARCHAR(1000) NOT NULL,
    `recipe_id` INT           NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_recipe_description_recipe1_idx` (`recipe_id` ASC),
    CONSTRAINT `fk_recipe_description_recipe1`
        FOREIGN KEY (`recipe_id`)
            REFERENCES `recipe` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
